url: https://github.com/prometheus-community/helm-charts.git
subdirectory: charts/kube-prometheus-stack
commit: 7c6906ca223344c06952007fda670c6c81e6d1da
version: 61.3.2-rancher.1
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/prometheus-community/helm-charts.git
      commit: 7c6906ca223344c06952007fda670c6c81e6d1da
      subdirectory: charts/kube-prometheus-stack/charts/crds/crds
    crdOptions:
      addCRDValidationToMainChart: true
      templateDirectory: crd-template
      useTarArchive: true
doNotRelease: false
